import Head from "next/head";
import Button3D from "../src/components/buttons/Button3D";
import ButtonGradient from "../src/components/buttons/ButtonGradient";
import Card from "../src/components/cards/Card";
import CardOne from "../src/components/cards/CardOne";

import rocketLogo from "../public/rocket.svg";
import zombie from "../public/zombie.png";
import GradientText from "../src/components/texts/GradientText";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The tailwindcss components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="max-w-[80rem] mx-auto p-8 text-center bg-gradient-to-tr from-black to-stone-700 rounded-md bold text-4xl mt-2 text-black">
          <GradientText   
            text="LFG With Tailwindcss"
          />
        </div>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-sm shadow-red-200  ">
          <p className="text-center text-xl font-bold">Buttons</p>
          <Button3D
            text="WAGMI"
            onClick={() => console.log("Button Clicked")}
          />

          <ButtonGradient
            text="WAGMI"
            onClick={() => console.log("Button Clicked")}
          />
        </div>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-sm shadow-red-200  ">
          <p className="text-center text-xl font-bold">Cards</p>
          <Card
            title="How to live"
            description="The way you like but don't fuck others idiot."
            imageUrl={rocketLogo}
          />

          <CardOne
            title="What does Zombie means?"
            description="A will-less and speechless human held to have died and been supernaturally reanimated."
            imageUrl={zombie}
          />
        </div>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-md shadow-red-200  ">
        <p className="text-center text-xl font-bold">Texts</p>
          <GradientText 
            text="Tailwind Gradient Text"
          />
        </div>
      </main>
    </div>
  );
}
