import Head from "next/head";
import Button3D from "../src/components/buttons/Button3D";
import ButtonGradient from "../src/components/buttons/ButtonGradient";
import Card from "../src/components/cards/Card";
import CardOne from "../src/components/cards/CardOne";

import rocketLogo from "../public/rocket.svg";
import zombie from "../public/zombie.png";
import GradientText from "../src/components/texts/GradientText";
import ButtonHoverEffect from "../src/components/buttons/ButtonHoverEffect";

import CircularLoading from "../src/components/loading/CircularLoading";
import GradientCircularLoading from "../src/components/loading/GradientCircularLoading";
import FireNavbar from "../src/components/navigation/FireNavbar";
import { LfgCard } from "../src/components/cards/LfgCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The tailwindcss components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <FireNavbar/>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-sm shadow-red-200 rounded-xl">
          <p className="text-center text-white text-xl font-bold">Buttons</p>
          <div className="grid grid-cols-3 gap-4">
            <Button3D
              text="WAGMI"
              onClick={() => console.log("Button Clicked")}
            />

            <ButtonGradient
              text="WAGMI"
              onClick={() => console.log("Button Clicked")}
            />

            <ButtonHoverEffect
              text="WAGMI"
              onClick={() => console.log("Button Clicked")}
            />
          </div>
        </div>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-sm shadow-red-200  ">
          <p className="text-center text-xl font-bold">Cards</p>

         <LfgCard/>
    
          <Card
            title="How to live"
            description="The way you like but don't fuck others idiot."
            imageUrl={rocketLogo}
          />

          <CardOne
            title="What does Zombie means?"
            description="A will-less and speechless human held to have died and been supernaturally reanimated."
            imageUrl={zombie}
          />
        </div>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-md shadow-red-200  ">
          <p className="text-center text-xl font-bold">Texts</p>
          <GradientText text="Tailwind Gradient Text" />
        </div>

        <div className="mt-8 max-w-4xl mx-auto p-8 shadow-md shadow-red-200  ">
          <p className="text-center text-xl font-bold">Circular progress bar</p>
          <CircularLoading />
          <GradientCircularLoading />
        </div>

        
      </main>
    </div>
  );
}
